// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

/// <summary>
/// Hashtags created by users for categorizing and filtering products. Private by default, shareable with users, groups, or spaces.
/// </summary>
[Index("OwnerUserId", "TagName", Name = "UX_Hashtags_Owner_TagName", IsUnique = true)]
public partial class Hashtag
{
    /// <summary>
    /// Primary key for the hashtag.
    /// </summary>
    [Key]
    public Guid HashtagId { get; set; }

    /// <summary>
    /// The user who created and owns this hashtag.
    /// </summary>
    public Guid OwnerUserId { get; set; }

    /// <summary>
    /// The text/name of the hashtag.
    /// </summary>
    [Required]
    [StringLength(100)]
    public string TagName { get; set; }

    /// <summary>
    /// Optional description of this hashtag.
    /// </summary>
    [StringLength(500)]
    public string Description { get; set; }

    /// <summary>
    /// UI icon assigned to this hashtag.
    /// </summary>
    [StringLength(100)]
    public string Icon { get; set; }

    /// <summary>
    /// Color code (hex or CSS) for UI representation of this hashtag.
    /// </summary>
    [StringLength(20)]
    public string ColorCode { get; set; }

    /// <summary>
    /// Used to sort hashtags in the UI.
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// When the hashtag was created (UTC).
    /// </summary>
    [Precision(0)]
    public DateTime CreatedUtc { get; set; }

    /// <summary>
    /// Indicates whether the hashtag is active or archived.
    /// </summary>
    public bool IsActive { get; set; }

    [InverseProperty("Hashtag")]
    public virtual ICollection<HashtagProductLink> HashtagProductLinks { get; set; } = new List<HashtagProductLink>();

    [InverseProperty("Hashtag")]
    public virtual ICollection<HashtagShare> HashtagShares { get; set; } = new List<HashtagShare>();

    [ForeignKey("OwnerUserId")]
    [InverseProperty("Hashtags")]
    public virtual User OwnerUser { get; set; }
}