// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

/// <summary>
/// Links hashtags to products. Each row indicates that a user assigned a specific hashtag to a product.
/// </summary>
public partial class HashtagProductLink
{
    /// <summary>
    /// Primary key for this hashtag-to-product link.
    /// </summary>
    [Key]
    public Guid HashtagProductLinkId { get; set; }

    /// <summary>
    /// References the hashtag assigned to a product.
    /// </summary>
    public Guid HashtagId { get; set; }

    /// <summary>
    /// References the product that the hashtag is linked to.
    /// </summary>
    public Guid ProductId { get; set; }

    /// <summary>
    /// The user who added this hashtag to the product.
    /// </summary>
    public Guid AddedByUserId { get; set; }

    /// <summary>
    /// UTC timestamp when the hashtag was assigned to the product.
    /// </summary>
    [Precision(0)]
    public DateTime AddedUtc { get; set; }

    [ForeignKey("AddedByUserId")]
    [InverseProperty("HashtagProductLinks")]
    public virtual User AddedByUser { get; set; }

    [ForeignKey("HashtagId")]
    [InverseProperty("HashtagProductLinks")]
    public virtual Hashtag Hashtag { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("HashtagProductLinks")]
    public virtual TrackedProduct Product { get; set; }
}