// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

/// <summary>
/// Records who a hashtag is shared with. Supports users, user groups, or spaces.
/// </summary>
public partial class HashtagShare
{
    /// <summary>
    /// Primary key for the share record.
    /// </summary>
    [Key]
    public Guid HashtagShareId { get; set; }

    /// <summary>
    /// Hashtag being shared.
    /// </summary>
    public Guid HashtagId { get; set; }

    /// <summary>
    /// The type of share target: User, UserGroup, or Space.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string TargetType { get; set; }

    /// <summary>
    /// ID of the target user, group, or space.
    /// </summary>
    public Guid TargetId { get; set; }

    /// <summary>
    /// Only populated when sharing directly with a user to speed up permission lookups.
    /// </summary>
    public Guid? UserId { get; set; }

    /// <summary>
    /// User who shared the hashtag.
    /// </summary>
    public Guid SharedByUserId { get; set; }

    /// <summary>
    /// When the hashtag was shared (UTC).
    /// </summary>
    [Precision(0)]
    public DateTime SharedUtc { get; set; }

    [ForeignKey("HashtagId")]
    [InverseProperty("HashtagShares")]
    public virtual Hashtag Hashtag { get; set; }

    [ForeignKey("SharedByUserId")]
    [InverseProperty("HashtagShares")]
    public virtual User SharedByUser { get; set; }
}