// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SmartSaverWeb.DataModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SmartSaverWeb.DataModels
{
    public partial interface Ipaynles_dbContextProcedures
    {
        Task<List<stp_ProductNotifications_GetSendQueueResult>> stp_ProductNotifications_GetSendQueueAsync(int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
