// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

public partial class Marketplace
{
    [Key]
    public Guid MarketplaceId { get; set; }

    [Required]
    [StringLength(100)]
    public string MarketplaceName { get; set; }

    [Required]
    [StringLength(50)]
    public string MarketplaceCode { get; set; }

    [StringLength(200)]
    public string BaseDomain { get; set; }

    [StringLength(10)]
    public string CountryCode { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedUtc { get; set; }

    [InverseProperty("Marketplace")]
    public virtual ICollection<TrackedProduct> TrackedProducts { get; set; } = new List<TrackedProduct>();

    [InverseProperty("Marketplace")]
    public virtual ICollection<UserMarketplace> UserMarketplaces { get; set; } = new List<UserMarketplace>();
}