// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

public partial class paynles_dbContext : DbContext
{
    public paynles_dbContext(DbContextOptions<paynles_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Hashtag> Hashtags { get; set; }

    public virtual DbSet<HashtagProductLink> HashtagProductLinks { get; set; }

    public virtual DbSet<HashtagShare> HashtagShares { get; set; }

    public virtual DbSet<Marketplace> Marketplaces { get; set; }

    public virtual DbSet<PriceHistory> PriceHistories { get; set; }

    public virtual DbSet<ProductNotification> ProductNotifications { get; set; }

    public virtual DbSet<Space> Spaces { get; set; }

    public virtual DbSet<SpaceMember> SpaceMembers { get; set; }

    public virtual DbSet<TrackedProduct> TrackedProducts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<UserGroupMember> UserGroupMembers { get; set; }

    public virtual DbSet<UserMarketplace> UserMarketplaces { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Hashtag>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("Hashtags created by users for categorizing and filtering products. Private by default, shareable with users, groups, or spaces."));

            entity.Property(e => e.HashtagId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasComment("Primary key for the hashtag.");
            entity.Property(e => e.ColorCode).HasComment("Color code (hex or CSS) for UI representation of this hashtag.");
            entity.Property(e => e.CreatedUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("When the hashtag was created (UTC).")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Hashtags_CreatedUtc");
            entity.Property(e => e.Description).HasComment("Optional description of this hashtag.");
            entity.Property(e => e.Icon).HasComment("UI icon assigned to this hashtag.");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("Indicates whether the hashtag is active or archived.")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Hashtags_IsActive");
            entity.Property(e => e.OwnerUserId).HasComment("The user who created and owns this hashtag.");
            entity.Property(e => e.SortOrder).HasComment("Used to sort hashtags in the UI.");
            entity.Property(e => e.TagName).HasComment("The text/name of the hashtag.");

            entity.HasOne(d => d.OwnerUser).WithMany(p => p.Hashtags)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Hashtags_OwnerUser");
        });

        modelBuilder.Entity<HashtagProductLink>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("Links hashtags to products. Each row indicates that a user assigned a specific hashtag to a product."));

            entity.Property(e => e.HashtagProductLinkId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasComment("Primary key for this hashtag-to-product link.");
            entity.Property(e => e.AddedByUserId).HasComment("The user who added this hashtag to the product.");
            entity.Property(e => e.AddedUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("UTC timestamp when the hashtag was assigned to the product.")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_HashtagProductLinks_AddedUtc");
            entity.Property(e => e.HashtagId).HasComment("References the hashtag assigned to a product.");
            entity.Property(e => e.ProductId).HasComment("References the product that the hashtag is linked to.");

            entity.HasOne(d => d.AddedByUser).WithMany(p => p.HashtagProductLinks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HashtagProductLinks_AddedBy");

            entity.HasOne(d => d.Hashtag).WithMany(p => p.HashtagProductLinks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HashtagProductLinks_Hashtag");

            entity.HasOne(d => d.Product).WithMany(p => p.HashtagProductLinks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HashtagProductLinks_Product");
        });

        modelBuilder.Entity<HashtagShare>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("Records who a hashtag is shared with. Supports users, user groups, or spaces."));

            entity.Property(e => e.HashtagShareId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasComment("Primary key for the share record.");
            entity.Property(e => e.HashtagId).HasComment("Hashtag being shared.");
            entity.Property(e => e.SharedByUserId).HasComment("User who shared the hashtag.");
            entity.Property(e => e.SharedUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("When the hashtag was shared (UTC).")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_HashtagShares_SharedUtc");
            entity.Property(e => e.TargetId).HasComment("ID of the target user, group, or space.");
            entity.Property(e => e.TargetType).HasComment("The type of share target: User, UserGroup, or Space.");
            entity.Property(e => e.UserId).HasComment("Only populated when sharing directly with a user to speed up permission lookups.");

            entity.HasOne(d => d.Hashtag).WithMany(p => p.HashtagShares)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HashtagShares_Hashtag");

            entity.HasOne(d => d.SharedByUser).WithMany(p => p.HashtagShares)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HashtagShares_SharedBy");
        });

        modelBuilder.Entity<Marketplace>(entity =>
        {
            entity.HasKey(e => e.MarketplaceId).HasName("PK__Marketpl__0386714D3AD873EB");

            entity.Property(e => e.MarketplaceId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<PriceHistory>(entity =>
        {
            entity.HasKey(e => e.PriceHistoryId).HasName("PK__PriceHis__A927CACB56728DE7");

            entity.Property(e => e.PriceHistoryId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.RecordedUtc).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Product).WithMany(p => p.PriceHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PriceHist__Produ__7B5B524B");
        });

        modelBuilder.Entity<ProductNotification>(entity =>
        {
            entity.Property(e => e.NotificationId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.DateSet).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductNotifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductNotifications_TrackedProducts");

            entity.HasOne(d => d.User).WithMany(p => p.ProductNotifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductNotifications_Users");
        });

        modelBuilder.Entity<Space>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("Organizational containers for user products, such as Pantry, Garage, Kitchen, or Business lists."));

            entity.Property(e => e.SpaceId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasComment("Primary key for the space.");
            entity.Property(e => e.ColorCode).HasComment("UI color code for this space.");
            entity.Property(e => e.CreatedUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("When this space was created (UTC).")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Spaces_CreatedUtc");
            entity.Property(e => e.Description).HasComment("Longer text describing the purpose of this space.");
            entity.Property(e => e.Icon).HasComment("UI icon assigned to this space.");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("Indicates if the space is active or archived.")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Spaces_IsActive");
            entity.Property(e => e.OwnerUserId).HasComment("User who owns/created this space.");
            entity.Property(e => e.SortOrder).HasComment("Sorting priority for UI ordering.");
            entity.Property(e => e.SpaceName).HasComment("Name of the space (Pantry, Garage, Kitchen, etc.).");
            entity.Property(e => e.SpaceType).HasComment("Classification of the space type (e.g., Pantry, Garage, Custom).");

            entity.HasOne(d => d.OwnerUser).WithMany(p => p.Spaces)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Spaces_OwnerUser");
        });

        modelBuilder.Entity<SpaceMember>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("Links users to spaces they have access to, including their role in that space."));

            entity.Property(e => e.SpaceMemberId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasComment("Primary key for the space membership.");
            entity.Property(e => e.AddedByUserId).HasComment("The user who added/invited this space member.");
            entity.Property(e => e.AddedUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("When the member was added (UTC).")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SpaceMembers_AddedUtc");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("Whether the membership is active.")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SpaceMembers_IsActive");
            entity.Property(e => e.Role).HasComment("Permission level: Viewer, Editor, or Admin.");
            entity.Property(e => e.SpaceId).HasComment("References the space the user belongs to.");
            entity.Property(e => e.UserId).HasComment("The user who is a member of this space.");

            entity.HasOne(d => d.AddedByUser).WithMany(p => p.SpaceMemberAddedByUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SpaceMembers_AddedBy");

            entity.HasOne(d => d.Space).WithMany(p => p.SpaceMembers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SpaceMembers_Space");

            entity.HasOne(d => d.User).WithMany(p => p.SpaceMemberUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SpaceMembers_User");
        });

        modelBuilder.Entity<TrackedProduct>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__TrackedP__B40CC6CDE8F99FC4");

            entity.Property(e => e.ProductId)
                .HasDefaultValueSql("(newsequentialid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__TrackedPr__Produ__73BA3083");
            entity.Property(e => e.AutoId).ValueGeneratedOnAdd();
            entity.Property(e => e.DateMarkedToDelete)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TrackedProducts_DateMarkedToDelete");
            entity.Property(e => e.GroupId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__TrackedPr__IsAct__778AC167");
            entity.Property(e => e.Keep).HasAnnotation("Relational:DefaultConstraintName", "DF_TrackedProducts_Keep");
            entity.Property(e => e.TimestampUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__TrackedPr__Times__76969D2E");
            entity.Property(e => e.ToDelete).HasAnnotation("Relational:DefaultConstraintName", "DF_TrackedProducts_ToDelete");

            entity.HasOne(d => d.Marketplace).WithMany(p => p.TrackedProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrackedPr__Marke__75A278F5");

            entity.HasOne(d => d.User).WithMany(p => p.TrackedProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrackedPr__UserI__74AE54BC");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C207CEEA4");

            entity.Property(e => e.UserId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedUtc).HasDefaultValueSql("(sysutcdatetime())");
        });

        modelBuilder.Entity<UserGroup>(entity =>
        {
            entity.Property(e => e.UserGroupId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserGroups_CreatedUtc");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserGroups_IsActive");

            entity.HasOne(d => d.GroupOwnerUser).WithMany(p => p.UserGroups)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroups_OwnerUser");
        });

        modelBuilder.Entity<UserGroupMember>(entity =>
        {
            entity.Property(e => e.UserGroupMemberId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserGroupMembers_IsActive");
            entity.Property(e => e.JoinedUtc)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserGroupMembers_JoinedUtc");

            entity.HasOne(d => d.UserGroup).WithMany(p => p.UserGroupMembers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupMembers_Group");

            entity.HasOne(d => d.User).WithMany(p => p.UserGroupMembers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupMembers_User");
        });

        modelBuilder.Entity<UserMarketplace>(entity =>
        {
            entity.HasKey(e => e.UserMarketplaceId).HasName("PK__UserMark__A05B049D667D5FE3");

            entity.Property(e => e.UserMarketplaceId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.GrantedUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.HasAccess).HasDefaultValue(true);

            entity.HasOne(d => d.Marketplace).WithMany(p => p.UserMarketplaces)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserMarke__Marke__01142BA1");

            entity.HasOne(d => d.User).WithMany(p => p.UserMarketplaces)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserMarke__UserI__00200768");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}