// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SmartSaverWeb.DataModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SmartSaverWeb.DataModels
{
    public partial class paynles_dbContext
    {
        private Ipaynles_dbContextProcedures _procedures;

        public virtual Ipaynles_dbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new paynles_dbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public Ipaynles_dbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class paynles_dbContextProcedures : Ipaynles_dbContextProcedures
    {
        private readonly paynles_dbContext _context;

        public paynles_dbContextProcedures(paynles_dbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<stp_ProductNotifications_GetSendQueueResult>> stp_ProductNotifications_GetSendQueueAsync(int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<stp_ProductNotifications_GetSendQueueResult>("EXEC @returnValue = [dbo].[stp_ProductNotifications_GetSendQueue] @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
