// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

[Table("PriceHistory")]
[Index("ProductId", Name = "IX_PriceHistory_ProductId")]
public partial class PriceHistory
{
    [Key]
    public Guid PriceHistoryId { get; set; }

    public Guid ProductId { get; set; }

    public DateTime RecordedUtc { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [StringLength(100)]
    public string Source { get; set; }

    [StringLength(50)]
    public string MarketplaceIdType { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("PriceHistories")]
    public virtual TrackedProduct Product { get; set; }
}