// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

public partial class ProductNotification
{
    [Key]
    public Guid NotificationId { get; set; }

    public Guid ProductId { get; set; }

    public Guid UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string RuleType { get; set; }

    [Required]
    [StringLength(50)]
    public string DropType { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal DropValue { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal NotificationValue { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal SavedPrice { get; set; }

    public DateTime DateSet { get; set; }

    public DateTime? DateModified { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductNotifications")]
    public virtual TrackedProduct Product { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ProductNotifications")]
    public virtual User User { get; set; }
}