// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

/// <summary>
/// Organizational containers for user products, such as Pantry, Garage, Kitchen, or Business lists.
/// </summary>
public partial class Space
{
    /// <summary>
    /// Primary key for the space.
    /// </summary>
    [Key]
    public Guid SpaceId { get; set; }

    /// <summary>
    /// User who owns/created this space.
    /// </summary>
    public Guid OwnerUserId { get; set; }

    /// <summary>
    /// Name of the space (Pantry, Garage, Kitchen, etc.).
    /// </summary>
    [Required]
    [StringLength(200)]
    public string SpaceName { get; set; }

    /// <summary>
    /// Classification of the space type (e.g., Pantry, Garage, Custom).
    /// </summary>
    [Required]
    [StringLength(100)]
    public string SpaceType { get; set; }

    /// <summary>
    /// When this space was created (UTC).
    /// </summary>
    [Precision(0)]
    public DateTime CreatedUtc { get; set; }

    /// <summary>
    /// Indicates if the space is active or archived.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Sorting priority for UI ordering.
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// UI icon assigned to this space.
    /// </summary>
    [StringLength(100)]
    public string Icon { get; set; }

    /// <summary>
    /// UI color code for this space.
    /// </summary>
    [StringLength(20)]
    public string ColorCode { get; set; }

    /// <summary>
    /// Longer text describing the purpose of this space.
    /// </summary>
    [StringLength(1000)]
    public string Description { get; set; }

    [ForeignKey("OwnerUserId")]
    [InverseProperty("Spaces")]
    public virtual User OwnerUser { get; set; }

    [InverseProperty("Space")]
    public virtual ICollection<SpaceMember> SpaceMembers { get; set; } = new List<SpaceMember>();
}