// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

/// <summary>
/// Links users to spaces they have access to, including their role in that space.
/// </summary>
public partial class SpaceMember
{
    /// <summary>
    /// Primary key for the space membership.
    /// </summary>
    [Key]
    public Guid SpaceMemberId { get; set; }

    /// <summary>
    /// References the space the user belongs to.
    /// </summary>
    public Guid SpaceId { get; set; }

    /// <summary>
    /// The user who is a member of this space.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Permission level: Viewer, Editor, or Admin.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Role { get; set; }

    /// <summary>
    /// The user who added/invited this space member.
    /// </summary>
    public Guid AddedByUserId { get; set; }

    /// <summary>
    /// When the member was added (UTC).
    /// </summary>
    [Precision(0)]
    public DateTime AddedUtc { get; set; }

    /// <summary>
    /// Whether the membership is active.
    /// </summary>
    public bool IsActive { get; set; }

    [ForeignKey("AddedByUserId")]
    [InverseProperty("SpaceMemberAddedByUsers")]
    public virtual User AddedByUser { get; set; }

    [ForeignKey("SpaceId")]
    [InverseProperty("SpaceMembers")]
    public virtual Space Space { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("SpaceMemberUsers")]
    public virtual User User { get; set; }
}