// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartSaverWeb.DataModels
{
    public partial class stp_ProductNotifications_GetSendQueueResult
    {
        public Guid NotificationId { get; set; }
        public Guid UserId { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
        public Guid ProductId { get; set; }
        [StringLength(100)]
        public string MarketplaceProductCode { get; set; }
        [StringLength(500)]
        public string Title { get; set; }
        [Column("PriceSeen", TypeName = "decimal(18,2)")]
        public decimal? PriceSeen { get; set; }
        [StringLength(50)]
        public string RuleType { get; set; }
        [StringLength(50)]
        public string DropType { get; set; }
        [Column("DropValue", TypeName = "decimal(18,2)")]
        public decimal DropValue { get; set; }
        [Column("SavedPrice", TypeName = "decimal(18,2)")]
        public decimal SavedPrice { get; set; }
        [Column("NotificationValue", TypeName = "decimal(18,2)")]
        public decimal NotificationValue { get; set; }
        public DateTime DateSet { get; set; }
        [StringLength(1000)]
        public string ImageUrl { get; set; }
        [StringLength(100)]
        public string MarketplaceName { get; set; }
    }
}
