// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

[Index("MarketplaceProductCode", Name = "IX_TrackedProducts_Code")]
[Index("MarketplaceId", Name = "IX_TrackedProducts_MarketplaceId")]
[Index("UserId", Name = "IX_TrackedProducts_UserId")]
public partial class TrackedProduct
{
    [Key]
    public Guid ProductId { get; set; }

    public Guid UserId { get; set; }

    public Guid MarketplaceId { get; set; }

    [Required]
    [StringLength(100)]
    public string MarketplaceProductCode { get; set; }

    [Required]
    [StringLength(50)]
    public string MarketplaceIdType { get; set; }

    [StringLength(500)]
    public string Title { get; set; }

    [StringLength(1000)]
    public string ImageUrl { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PriceSeen { get; set; }

    [StringLength(50)]
    public string RecordType { get; set; }

    public DateTime TimestampUtc { get; set; }

    [StringLength(100)]
    public string Source { get; set; }

    public bool IsActive { get; set; }

    [StringLength(50)]
    public string IpAddress { get; set; }

    [StringLength(100)]
    public string ParentProductId { get; set; }

    [Column("AutoID")]
    public int AutoId { get; set; }

    [Required]
    [StringLength(100)]
    public string GroupId { get; set; }

    public bool Keep { get; set; }

    public bool ToDelete { get; set; }

    public DateTime DateMarkedToDelete { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<HashtagProductLink> HashtagProductLinks { get; set; } = new List<HashtagProductLink>();

    [ForeignKey("MarketplaceId")]
    [InverseProperty("TrackedProducts")]
    public virtual Marketplace Marketplace { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<PriceHistory> PriceHistories { get; set; } = new List<PriceHistory>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductNotification> ProductNotifications { get; set; } = new List<ProductNotification>();

    [ForeignKey("UserId")]
    [InverseProperty("TrackedProducts")]
    public virtual User User { get; set; }
}