// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

public partial class UserGroupMember
{
    [Key]
    public Guid UserGroupMemberId { get; set; }

    public Guid UserGroupId { get; set; }

    public Guid UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Role { get; set; }

    [Precision(0)]
    public DateTime JoinedUtc { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserGroupMembers")]
    public virtual User User { get; set; }

    [ForeignKey("UserGroupId")]
    [InverseProperty("UserGroupMembers")]
    public virtual UserGroup UserGroup { get; set; }
}