// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

[Index("Email", Name = "UQ__Users__A9D105346F26ED1E", IsUnique = true)]
public partial class User
{
    [Key]
    public Guid UserId { get; set; }

    [Required]
    [StringLength(200)]
    public string Email { get; set; }

    [StringLength(200)]
    public string DisplayName { get; set; }

    [StringLength(255)]
    public string PasswordHash { get; set; }

    public DateTime CreatedUtc { get; set; }

    public DateTime? LastLoginUtc { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("AddedByUser")]
    public virtual ICollection<HashtagProductLink> HashtagProductLinks { get; set; } = new List<HashtagProductLink>();

    [InverseProperty("SharedByUser")]
    public virtual ICollection<HashtagShare> HashtagShares { get; set; } = new List<HashtagShare>();

    [InverseProperty("OwnerUser")]
    public virtual ICollection<Hashtag> Hashtags { get; set; } = new List<Hashtag>();

    [InverseProperty("User")]
    public virtual ICollection<ProductNotification> ProductNotifications { get; set; } = new List<ProductNotification>();

    [InverseProperty("AddedByUser")]
    public virtual ICollection<SpaceMember> SpaceMemberAddedByUsers { get; set; } = new List<SpaceMember>();

    [InverseProperty("User")]
    public virtual ICollection<SpaceMember> SpaceMemberUsers { get; set; } = new List<SpaceMember>();

    [InverseProperty("OwnerUser")]
    public virtual ICollection<Space> Spaces { get; set; } = new List<Space>();

    [InverseProperty("User")]
    public virtual ICollection<TrackedProduct> TrackedProducts { get; set; } = new List<TrackedProduct>();

    [InverseProperty("User")]
    public virtual ICollection<UserGroupMember> UserGroupMembers { get; set; } = new List<UserGroupMember>();

    [InverseProperty("GroupOwnerUser")]
    public virtual ICollection<UserGroup> UserGroups { get; set; } = new List<UserGroup>();

    [InverseProperty("User")]
    public virtual ICollection<UserMarketplace> UserMarketplaces { get; set; } = new List<UserMarketplace>();
}