// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

[Index("MarketplaceId", Name = "IX_UserMarketplaces_MarketplaceId")]
[Index("UserId", Name = "IX_UserMarketplaces_UserId")]
public partial class UserMarketplace
{
    [Key]
    public Guid UserMarketplaceId { get; set; }

    public Guid UserId { get; set; }

    public Guid MarketplaceId { get; set; }

    public bool HasAccess { get; set; }

    [StringLength(50)]
    public string AccessLevel { get; set; }

    public DateTime GrantedUtc { get; set; }

    public DateTime? RevokedUtc { get; set; }

    [StringLength(200)]
    public string GrantedBy { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    [ForeignKey("MarketplaceId")]
    [InverseProperty("UserMarketplaces")]
    public virtual Marketplace Marketplace { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserMarketplaces")]
    public virtual User User { get; set; }
}