// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartSaverWeb.DataModels;

public partial class UserGroup
{
    [Key]
    public Guid UserGroupId { get; set; }

    public Guid GroupOwnerUserId { get; set; }

    [Required]
    [StringLength(200)]
    public string GroupName { get; set; }

    [StringLength(100)]
    public string GroupType { get; set; }

    [StringLength(50)]
    public string PrivacyLevel { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [StringLength(100)]
    public string Icon { get; set; }

    [StringLength(20)]
    public string ColorCode { get; set; }

    public int? SortOrder { get; set; }

    [Precision(0)]
    public DateTime CreatedUtc { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("GroupOwnerUserId")]
    [InverseProperty("UserGroups")]
    public virtual User GroupOwnerUser { get; set; }

    [InverseProperty("UserGroup")]
    public virtual ICollection<UserGroupMember> UserGroupMembers { get; set; } = new List<UserGroupMember>();
}